.PHONY: default # Diz que default não é nenhum tipo de arquivo físico no computador

# Por padrão, o comando make irá executar o primeiro alvo ---> default

default:
	echo 'hello world'
	@echo 'hello world' 

# @ faz com que o comando não seja mostrado no terminal